version: 0.2
env:
  variables:
    LAMBDA_FUNCTION_NAME: "LambdaSample2"
    PROJECT_FILE_DIR_PATH: "LambdaSample2/src/LambdaSample2"
phases:
  install:
    commands:
    - wget https://dot.net/v1/dotnet-install.sh
    - chmod +x dotnet-install.sh
    - ./dotnet-install.sh -c 6.0 --install-dir $HOME/.dotnet
    - export DOTNET_ROOT=$HOME/.dotnet
    - export PATH=$PATH:$DOTNET_ROOT
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Restore started on `date`
      - export PATH="$PATH:$DOTNET_ROOT"
      - cd $CODEBUILD_SRC_DIR/$PROJECT_FILE_DIR_PATH
      - dotnet clean
      - dotnet restore
  build:
    commands:
      - echo Deployment started on `date` for function $LAMBDA_FUNCTION_NAME
      - dotnet new --install Amazon.Lambda.Templates::*
      - dotnet tool install -g Amazon.Lambda.Tools
      - dotnet tool update -g Amazon.Lambda.Tools
      - cd $CODEBUILD_SRC_DIR/$PROJECT_FILE_DIR_PATH
      - aws --version
      - dotnet --version
      - echo $CODEBUILD_SRC_DIR
      - echo $PROJECT_FILE_DIR_PATH
      - dotnet lambda deploy-function $LAMBDA_FUNCTION_NAME
artifacts:
  files: '**/*'
  name: BuildArtifacts
  discard-paths: yes
  base-directory: dist


